### ISSUE TITLE
关于属性attributes  DeepFashion Dataset的分类训练

### ISSUE THREAD

**Issue by zxczhkzxc** [dcarnino/deep-fashion-detection#1]
您好   看到你的category的训练实现3个分类，想问下你有没有研究属性的分类比如按照 color, style and pattern这些分类，结合DeepFashion数据集进行训练？望回复 谢谢

**Comment by dcarnino** [comment]
Hi, it is not in the scope of this project to perform the classification of attributes such as the color, style and pattern of clothes. Feel free to fork this repository if you wish to extend it.
